version: '3.7'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Password123
      MYSQL_ROOT_USE: root
      MYSQL_DATABASE: db_api
    ports:
      - '3306:3306'
    volumes:
      - C:/docker_databases:/var/lib/mysql
    restart: always
